### ISSUE TITLE
Synk report fix: Update docker/Dockerfile

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-profile#29]
Use latest LTS version.

Needs the docker file base image "node" updated to node:21.6+ or so.

Check here:

https://app.snyk.io/org/po.daac/projects

podaac/hitide-profile

**Comment by jamesfwood** [comment]
@jbyrne6 node 21.6 failing.  Please test locally first.

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test HiTIDE (4.17.2-RC.4) in UAT, with the new HiTIDE Profile (4.10.1-rc.10) version.

Thanks!

**Comment by davidcolemanjpl** [comment]
**HiTIDE UAT v4.17.2-RC.4
HiTIDE profile v4.10.1-rc.1**

HiTIDE functionality / subsetting seems to be currently okay in UAT.


I'll need more deets regarding this requirement testing / acceptance criteria. 

It seems like the base image node:21.6 still shows issues in SNYK: (podaac/hitide-profile  docker/Dockerfile)
https://app.snyk.io/org/po.daac/project/0a3f1fd9-06b5-4531-9f06-b2185b894722?action=retest&success=false&result=FAILED_RETEST


![HiTIDE profile - SNYK report - 050124](https://github.com/podaac/hitide-profile/assets/57456095/7135d1b8-1ac2-434f-b31f-0ee5d30bb019)

Functionality passed in HiTIDE UAT:
![UAT-test-latestcode-HiTIDE-1](https://github.com/podaac/hitide-profile/assets/57456095/24965a3f-f3fc-48f8-a9ac-9108d7af99a3)

**Comment by davidcolemanjpl** [comment]
**HiTIDE UAT v4.17.2-RC.4
HiTIDE profile v4.10.1-rc.1**

Updated AC, per DEV:
"check the network tab to make sure there is only one graphql call to get all collection data instead of one rest api call per collection. And to make sure collection resolution is present and thumbnails work still."


**FAIL:**
Collections in HiTIDE UAT UI currently have no associated Metadata & Granule Availability Image.
Also, Spatial Resolution  is listed as 'Not Available' for several cloud datasets:

_**see cloud datasets**_:
AMSRE-REMSS-L2P-v7a
ALTIKA_SARAL_L2_OST_XOGDR 
AMSR2-REMSS-L2P-v8.2 
AMSR2-REMSS-L2P_RT-v8.2
AMSR2-REMSS-L2P_RT_v8a 
VIIRS_NPP-STAR-L2P-v2.80
VIIRS_N20-NAVO-L2P-v3.0
ASCATA-L2-25km
ASCATB-L2-Coastal
ASCATB_ESDR_L2_WIND_STRESS_V1.1
ASCATC-L2-25km
ASCATC-L2-Coastal
AVHRRF_MA-STAR-L2P-v2.80
AVHRRF_MB-STAR-L2P-v2.80
AVHRRF_MC-STAR-L2P-v2.80
AVHRRMTA_G-NAVO-L2P-v2.0
AVHRRMTB_G-NAVO-L2P-v2.0
AVHRRMTC_G-NAVO-L2P-v2.0
AVHRR_SST_METOP_B-OSISAF-L2P-v1.0
CYGNSS_NOAA_L2_SWSP_25KM_V1.2
JASON-1_L2_OST_GPN_E
JASON-1_L2_OST_GPR_E
JASON-1_L2_OST_GPS_E
MERGED_TP_J1_OSTM_OST_CYCLES_V42
MODIS_A-JPL-L2P-v2019.0
MODIS_T-JPL-L2P-v2019.0
N21-VIIRS-L2P-ACSPO-v2.80
OS2_OSCAT_LEVEL_2B_OWV_COMP_12_V2
PRIM_SMAP_L2_V1
QSCAT_LEVEL_2B_OWV_COMP_12_KUSST_LCRES_4.1
QSCAT_LEVEL_2B_OWV_COMP_12_LCR_3.1
RSCAT_LEVEL_2B_OWV_CLIM_12_V2 
SMAP_RSS_L2_SSS_V4
SMAP_RSS_L2_SSS_V5
SMAP_RSS_L2_SSS_V6
(***ALL SWOT collections affected)
SWOT_L2_LR_SSH_BASIC_1.0
SWOT_L2_LR_SSH_BASIC_1.1
SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_1.0
SWOT_L2_LR_SSH_EXPERT_1.1
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0
TMI-REMSS-L2P-v4
VIIRS_N20-NAVO-L2P-v3.0 (duplicate collection in UI)
VIIRS_N20-NAVO-L2P-v3.0
VIIRS_N20-OSPO-L2P-v2.61
VIIRS_N20-STAR-L2P-v2.80
VIIRS_N21-NAVO-L2P-v3.0
VIIRS_NPP-JPL-L2P-v2016.2


![no resolution - altika in hitide UAT-1](https://github.com/podaac/hitide-profile/assets/57456095/b7277c2d-896a-406f-99bf-5ed790a181ad)


note: 
2 graphql calls ('xhr' and 'preflight' types) display in the network tab f/when user selects a dataset in UI:
(same behavior is currently in HiTIDE OPS UI (v4.17.1))



![2 graphql calls when dataset selected-1](https://github.com/podaac/hitide-profile/assets/57456095/91a0ed6c-e884-4448-b7c2-268a7849f762)
![21-graphql calls-network tab](https://github.com/podaac/hitide-profile/assets/57456095/dce8248f-aee6-4d55-9dac-c0c354c39a35)

**Comment by jamesfwood** [comment]
@davidcolemanjpl Hi David.  Please retest this in UAT again.  Should be fixed.
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI UAT v**4.17.2-RC.5**
HiTIDE-profile v**4.10.1-rc.10**

The graphql calls ('xhr' type) to get all collection data seems to currently function okay in HiTIDE-UI UAT.  
The collections Spatial Resolution is present and the associated dataset thumbnails appear okay.


**_NOTE_**:  the following datasets Spatial Resolution in UAT is noted as 'Not Applicable':
AQUARIUS_L2_SSS_CAP_V5 
AQUARIUS_L2_SSS_V5
JASON-1_L2_OST_GPS_E
JASON-1_L2_OST_GPN_E
JASON-1_L2_OST_GPR_E
SWOT_L2_NALT_GDR_SGDR_2.0
SWOT_L2_NALT_GDR_SSHA_2
SWOT_L2_NALT_IGDR_GDR_2.0
SWOT_L2_NALT_IGDR_SGDR_2.0
SWOT_L2_NALT_IGDR_SSHA_2.0
SWOT_L2_NALT_OGDR_GDR_2.0
SWOT_L2_NALT_OGDR_SSHA_2.0
SWOT_L2_RAD_IGDR_2.0
SWOT_L2_RAD_OGDR_2.0



_Side Observation:_(Blocker)
Errors currently displayed today in UI console
(See JIRA PODAAC-6247)

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test this in UAT.   Updated hitide-profile version in UAT.
David, can you ask @jimmie how to update that Synk report?

**Comment by davidcolemanjpl** [comment]
HITIDE UAT UI V4.17.2-RC.9
**_HiTIDE profile: v4.10.1-rc.13_**
chrome v125.0.6422.142 (Official Build) (arm64)

***I'll need more details / information regarding the "SNYK update" requirement


note:
JIRA **PODAAC-6247** is still an issue in this version, 500 (Internal Server Error) and 400 (Bad Request) errors still display in UI console.


note2:
Currently, in SNYK,  there are 3 related HiTIDE Profile Projects / targets:
_podaac/hitide profile
/podaac/hitide-profile.git
podaac/hitde-profile_

![HiTIDEProfile-TargetsinSNYK(3)](https://github.com/podaac/hitide-profile/assets/57456095/a5d63c58-a7f7-4af7-aba7-ef9b16cbc1e1)

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl Please test again in HiTIDE UAT
Thanks!
Fixing the 500 error in another ticket.

**Comment by davidcolemanjpl** [comment]
HITIDE (**UAT**) UI v4.17.2-rc.10
HiTIDE-profile: v4.10.1-rc.15
chrome v127.0.6533.74 (Official Build) (arm64)
snyk- hitide-profile Dockerfile Base Image = node:21.6


The graphql calls ('xhr' type) to get all collection data currently seems to function as expected in HiTIDE-UI UAT.


**Test Failed**:

The following collection in HiTIDE UAT UI currently has no associated Metadata & Granule Availability Image:
**_MERGED_TP_J1_OSTM_OST_CYCLES_V42_** - image broken 

Spatial Resolution =  Not **Available** 
**_MERGED_TP_J1_OSTM_OST_CYCLES_V52_**

![Image](https://github.com/user-attachments/assets/e2ae7866-c45d-4b50-b3aa-d894f9a53fb7)





NOTE:
**_Metadata & Granule Availability Spatial Resolution_** =  'Not **Applicable**' in HiTIDE-UI :

_**AQUARIUS_L2_SSS_CAP_V5
AQUARIUS_L2_SSS_V5
JASON-1_L2_OST_GPN_E
JASON-1_L2_OST_GPR_E
JASON-1_L2_OST_GPS_E
PRIM_SMAP_L2_V1
SWOT_L2_NALT_GDR_SGDR_2.0
SWOT_L2_NALT_GDR_SSHA_2.0
SWOT_L2_NALT_IGDR_GDR_2.0
SWOT_L2_NALT_IGDR_SGDR_2.0
SWOT_L2_NALT_IGDR_SSHA_2.0
SWOT_L2_NALT_IGDR_SSHA_2.0
SWOT_L2_NALT_OGDR_SSHA_2.0
SWOT_L2_RAD_OGDR_2.0
SWOT_L2_RAD_IGDR_2.0**_



NOTE2:
**Side Observation**:(Blocker) - this issue will be addressed separately ; Errors currently display in HiTIDE-UI console when selecting dataset's info icon (See JIRA PODAAC-6247 / https://github.com/podaac/hitide-ui/issues/70)
- User can see 400/500 errors in console when selecting info icon for the following datasets:
**_ASCATC-L2-Coastal  
ASCATB-L2-Coastal 
ASCATB-L2-25km
CYGNSS_L2_CDR_V1.0
PRIM_SMAP_L2_V1
SMAP_RSS_L2_SSS_V6
QSCAT_LEVEL_2B_OWV_COMP_12_KUSST_LCRES_4.1_**

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl please test again.  This ticket should be only to make sure hitide works with node 21.6.  All the collection issues should go into a new ticket.
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI UAT v4.17.2-rc.10
HiTIDE Profile  v4.10.1-rc.16
l2ss-py:2.11.0rc8
concise v0.9.0rc5 
Harmony (UAT) UI - v0.0.1075
snyk- hitide-profile Dockerfile Base Image = node:21.6

The graphql calls ('xhr' type) to get all collection data currently seems to function as expected in HiTIDE-UI UAT.

**_Test Complete_**

![snyk-docker-1](https://github.com/user-attachments/assets/96f3a40d-ee2c-424b-bdf8-f12f500bac5f)
![snyk-docker-2](https://github.com/user-attachments/assets/86165856-ebcb-4def-8870-1186a4f68e94)


__________________________________________________________________________________________________________________________________________________________________________________________________________________
**NOTE:** 
major issue still associated w/ this development ticket (SIT/UAT):

see [PODAAC-6406](https://jira.jpl.nasa.gov/browse/PODAAC-6406)

The following collection in HiTIDE UAT UI currently has no associated Metadata & Granule Availability Image:
MERGED_TP_J1_OSTM_OST_CYCLES_V42 - image broken

Spatial Resolution = Not Available
MERGED_TP_J1_OSTM_OST_CYCLES_V52
